### ISSUE TITLE
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'modifiesActor')

### ISSUE THREAD

**Issue by Sayshal** [krbz999/effectmacro#47]
D&D 3.1.2/Foundry 11, getting following error on long rest:
```
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'modifiesActor')
[Detected 2 packages: effectmacro, system:dnd5e]
    at Object.updateItem [as fn] (effect.mjs:102:27)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13738:13)
    at foundry.js:13711:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13711:33)
    at async Item5e.updateDocuments (commons.js:8001:23)
    at async Actor5e._rest (actor.mjs:2335:5)
updateItem @ effect.mjs:102
#call @ foundry.js:730
callAll @ foundry.js:687
callback @ foundry.js:13738
(anonymous) @ foundry.js:13711
#handleUpdateDocuments @ foundry.js:13711
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13458
await in _updateDocuments (async)
update @ commons.js:8677
await in update (async)
updateDocuments @ commons.js:8001
updateEmbeddedDocuments @ commons.js:8233
_rest @ actor.mjs:2335
await in _rest (async)
(anonymous) @ rest-workflow.js:241
```

**Comment by krbz999** [comment]
Please provide minimal steps to reproduce the issue.
